// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	purchase "github.com/ozonva/ova-purchase-api/internal/purchase"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddPurchase mocks base method.
func (m *MockRepo) AddPurchase(ctx context.Context, purchases purchase.Purchase) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPurchase", ctx, purchases)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPurchase indicates an expected call of AddPurchase.
func (mr *MockRepoMockRecorder) AddPurchase(ctx, purchases interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPurchase", reflect.TypeOf((*MockRepo)(nil).AddPurchase), ctx, purchases)
}

// AddPurchases mocks base method.
func (m *MockRepo) AddPurchases(ctx context.Context, purchases []purchase.Purchase) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPurchases", ctx, purchases)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPurchases indicates an expected call of AddPurchases.
func (mr *MockRepoMockRecorder) AddPurchases(ctx, purchases interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPurchases", reflect.TypeOf((*MockRepo)(nil).AddPurchases), ctx, purchases)
}

// DescribePurchase mocks base method.
func (m *MockRepo) DescribePurchase(ctx context.Context, purchaseId uint64) (*purchase.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribePurchase", ctx, purchaseId)
	ret0, _ := ret[0].(*purchase.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribePurchase indicates an expected call of DescribePurchase.
func (mr *MockRepoMockRecorder) DescribePurchase(ctx, purchaseId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribePurchase", reflect.TypeOf((*MockRepo)(nil).DescribePurchase), ctx, purchaseId)
}

// ListPurchases mocks base method.
func (m *MockRepo) ListPurchases(ctx context.Context, limit, offset uint) ([]purchase.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPurchases", ctx, limit, offset)
	ret0, _ := ret[0].([]purchase.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPurchases indicates an expected call of ListPurchases.
func (mr *MockRepoMockRecorder) ListPurchases(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPurchases", reflect.TypeOf((*MockRepo)(nil).ListPurchases), ctx, limit, offset)
}

// RemovePurchase mocks base method.
func (m *MockRepo) RemovePurchase(ctx context.Context, purchaseId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePurchase", ctx, purchaseId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePurchase indicates an expected call of RemovePurchase.
func (mr *MockRepoMockRecorder) RemovePurchase(ctx, purchaseId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePurchase", reflect.TypeOf((*MockRepo)(nil).RemovePurchase), ctx, purchaseId)
}

// UpdatePurchase mocks base method.
func (m *MockRepo) UpdatePurchase(ctx context.Context, purchases purchase.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePurchase", ctx, purchases)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePurchase indicates an expected call of UpdatePurchase.
func (mr *MockRepoMockRecorder) UpdatePurchase(ctx, purchases interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePurchase", reflect.TypeOf((*MockRepo)(nil).UpdatePurchase), ctx, purchases)
}
